// SPDX-License-Identifier: GPL-3.0-or-later WITH LicenseRef-cardkit-ads-exception
package io.github.rotundtapir.fivehundred.ui

import io.github.rotundtapir.cardkit.core.Card
import io.github.rotundtapir.cardkit.core.Joker
import io.github.rotundtapir.cardkit.core.Rank
import io.github.rotundtapir.cardkit.core.Suit
import io.github.rotundtapir.cardkit.core.of
import io.github.rotundtapir.fivehundred.engine.Bid
import io.github.rotundtapir.fivehundred.engine.Trump

/**
 * The interactive "How to play" tutorial: a real 4-player hand on a fixed seed, replayed through the
 * normal [io.github.rotundtapir.fivehundred.GameViewModel] wiring, with a guidance panel explaining
 * every human decision and only the scripted action enabled — so the hand always follows the script.
 *
 * The script below is the exact trace of seed [TUTORIAL_SEED] with the default table (4 players,
 * 2 teams, misère and no-trumps enabled) and the standard bots at seats 1–3. It was generated by
 * `ai/src/test/.../TutorialTraceGenerator.kt` (kept, @Disabled, as documentation):
 *
 *   Bots: seat 1 = Olive, seat 2 = Mabel (your partner), seat 3 = Edna
 *   Your deal: 10♠ J♠ J♦ 9♠ 5♣ K♠ 7♦ Q♥ Joker A♥ · kitty: Q♣ 8♣ K♥
 *   Auction: Olive Pass · Mabel Pass · Edna Pass · You 7♠
 *   Discards: 5♣ 7♦ 8♣
 *   Tricks (your card first marked): Joker✓ · J♠✓ · K♠ (Olive's J♣ wins) · J♦ (Olive wins) ·
 *     Q♣ (Mabel wins) · Q♥ (Mabel wins) · K♥✓ · 10♠✓ · 9♠✓ · A♥✓  — 8 tricks, 7♠ made, +140/+20.
 *
 * If the game ever deviates from this script, the seed or the ViewModel wiring changed — regenerate.
 */
const val TUTORIAL_SEED = 9L

/** One human decision in the scripted tutorial hand, with the advice shown before it is taken. */
sealed interface TutorialStep {
    val advice: String

    /** Show the Joker → J♠ → J♣ → A♠ trump-order card row under the advice. */
    val showTrumpOrder: Boolean get() = false

    /** The auction: only [bid] is enabled. */
    data class BidStep(val bid: Bid, override val advice: String) : TutorialStep

    /** The kitty exchange: only [cards] are selectable, and all three must be selected. */
    data class DiscardStep(val cards: List<Card>, override val advice: String) : TutorialStep

    /** A trick: only [card] is playable. */
    data class PlayStep(
        val card: Card,
        override val advice: String,
        override val showTrumpOrder: Boolean = false,
    ) : TutorialStep
}

/** A titled page of tutorial prose, shown in the paged card dialogs before and after the hand. */
data class TutorialPage(val title: String, val body: String)

/** The primer's hand-over page: what the scripted tutorial hand is about to do. */
const val TUTORIAL_INTRO =
    "Now see it in play. You'll play one practice hand against three bots, guided at every " +
        "decision: what to bid, what to discard, and which card to play, with the reason why. " +
        "Only the recommended move is enabled at each step, so you can't go wrong."

/**
 * The primer paged through before the practice hand deals: what the game is, what a trick is, why
 * you bid and what the kitty is, and how to size up a hand — the concepts the scripted advice then
 * applies. New-player feedback drove this: the hand's advice alone assumed all of it as known.
 */
val tutorialPrologue: List<TutorialPage> = listOf(
    TutorialPage(
        title = "Welcome to 500",
        body = "500 is a trick-taking card game: four players in two teams, and your partner " +
            "sits across the table from you. Each hand, every player is dealt 10 cards, and " +
            "the two teams compete to win tricks with them. The first team to reach 500 " +
            "points wins the game.",
    ),
    TutorialPage(
        title = "What's a trick?",
        body = "A trick is one card from each player, played in turn around the table, and the " +
            "best card takes all four. You must play a card of the suit that was led " +
            "whenever you have one. The highest card of that suit wins the trick, unless a " +
            "player with none of the suit plays a trump, which beats everything. Whoever wins " +
            "a trick leads the next. Ten cards each means every hand is a fight over exactly " +
            "10 tricks.",
    ),
    TutorialPage(
        title = "Bidding and the kitty",
        body = "Each hand opens with an auction. A bid like 7♠ is a promise: \"my team will " +
            "win at least 7 of the 10 tricks, with spades as trumps.\" The highest bid becomes " +
            "the contract, and the winning bidder gets a reward: the kitty, the 3 cards left " +
            "over from the deal, picked up into hand with any 3 cards discarded in return. " +
            "Make the contract and your team scores its value; fall short and you lose that " +
            "much instead, while the defending team scores 10 points for every trick it takes.",
    ),
    TutorialPage(
        title = "Sizing up a hand",
        body = "Bid only what your cards can back up. Count your likely winners: the Joker " +
            "(the highest trump in the game), high trumps, and aces. Holding lots of trumps " +
            "is worth extra: once the other players' trumps run out, even your small ones " +
            "win tricks. Then allow roughly one more for help you can't see yet: the kitty " +
            "will improve your hand, and your partner's cards usually chip in. Six winners " +
            "in hand is a sound bid of 7. Nothing high and no long suit? Pass, and score " +
            "10 a trick defending while the other side overreaches.",
    ),
    TutorialPage(
        title = "A practice hand",
        body = TUTORIAL_INTRO,
    ),
)

/** Two bids the scripted hand never used, touched on before the tutorial closes. */
val tutorialEpilogue: List<TutorialPage> = listOf(
    TutorialPage(
        title = "One more bid: Misère",
        body = "Misère is a contract to win NO tricks at all, worth 250 points if you manage " +
            "it. It's played with no trumps, your partner sits the hand out, and it can only " +
            "be bid once the auction has reached seven (7♠ or higher). Tempting when your hand " +
            "is nothing but low cards.",
    ),
    TutorialPage(
        title = "And no-trumps",
        body = "You can also bid with no trump suit at all (6NT up to 10NT, the top of each " +
            "level). With no trumps there are no bowers: the highest card of the led suit wins " +
            "every trick, except the Joker, which is the one and only trump. 10NT is the most " +
            "valuable contract in the game at 520 points.",
    ),
)

/** Shown after the scripted hand has been scored. */
const val TUTORIAL_COMPLETION =
    "You bid 7♠, drew trumps with the Joker and the bowers, and took eight tricks with your " +
        "partner: contract made, +140 points. You've now seen bidding, the kitty exchange, " +
        "the bowers, following suit, and playing with a partner. " +
        "Start a real game from the home screen when you're ready!"

/**
 * Every human decision of the tutorial hand, in order: 1 bid, 1 discard, 10 plays.
 * The advice is grounded in the actual trace documented above — do not edit one without the other.
 */
val tutorialSteps: List<TutorialStep> = listOf(
    TutorialStep.BidStep(
        bid = Bid.Named(7, Trump.SPADES),
        advice = "Time to bid: count your likely winners. The Joker, the J♠ (the \"right " +
            "bower\", more on that soon), K♠, 10♠ and 9♠ are five strong spades; the A♥ " +
            "makes six. The seventh? Winning the auction gets you the kitty's three cards to " +
            "improve your hand, and your partner's cards usually chip in a trick or so. " +
            "Everyone else has passed, so bid 7♠.",
    ),
    TutorialStep.DiscardStep(
        cards = listOf(
            Rank.FIVE of Suit.CLUBS,
            Rank.SEVEN of Suit.DIAMONDS,
            Rank.EIGHT of Suit.CLUBS,
        ),
        advice = "Winning the auction gave you the kitty: Q♣, 8♣ and K♥. Keep every trump and " +
            "your high cards, and throw the three weakest odd cards: the 5♣, 7♦ and 8♣. " +
            "Short side suits let you trump those suits sooner. " +
            "Swipe the hand sideways if a card is out of view.",
    ),
    TutorialStep.PlayStep(
        card = Joker,
        advice = "As declarer you lead the first trick. Start with the Joker, the highest trump " +
            "in the game. It cannot lose, and it pulls a trump out of every other hand.",
    ),
    TutorialStep.PlayStep(
        card = Rank.JACK of Suit.SPADES,
        advice = "Now the most important rule in 500: in the trump suit, the JACKS OUTRANK THE " +
            "ACE. Your J♠ is the \"right bower\", the second-highest trump after the Joker. " +
            "Lead it, and even the A♠ cannot beat it. Watch it happen.",
        showTrumpOrder = true,
    ),
    TutorialStep.PlayStep(
        card = Rank.KING of Suit.SPADES,
        advice = "Same rule, other Jack: the J♣ is not really a club. As the other BLACK Jack " +
            "it becomes a spade, the \"left bower\", the third-highest trump. It's still out " +
            "there, and it beats your K♠. Lead the King anyway: losing it now flushes the last " +
            "big trump for cheap.",
        showTrumpOrder = true,
    ),
    TutorialStep.PlayStep(
        card = Rank.JACK of Suit.DIAMONDS,
        advice = "You must follow suit when you can: Olive led diamonds and the J♦ is your only " +
            "one. Here it's just an ordinary Jack; only the same-colour J♣ becomes a trump.",
    ),
    TutorialStep.PlayStep(
        card = Rank.QUEEN of Suit.CLUBS,
        advice = "Forced again: the Q♣ is your only club. Your partner Mabel's K♣ is winning " +
            "the trick, and her tricks count towards your contract too.",
    ),
    TutorialStep.PlayStep(
        card = Rank.QUEEN of Suit.HEARTS,
        advice = "You're out of clubs, so you could trump, but Mabel's A♣ already has the trick " +
            "and she's your partner. Never trump your partner's winner: throw your lowest card, " +
            "the Q♥.",
    ),
    TutorialStep.PlayStep(
        card = Rank.KING of Suit.HEARTS,
        advice = "Mabel's J♥ is heading for the trick, so play your cheaper heart, the K♥. " +
            "Either way this trick stays on your side, and the A♥ is saved as a certain " +
            "winner for later.",
    ),
    TutorialStep.PlayStep(
        card = Rank.TEN of Suit.SPADES,
        advice = "Count the trumps: every one outside your hand has now been played. Your 10♠ " +
            "and 9♠ are unbeatable, so lead the 10♠.",
    ),
    TutorialStep.PlayStep(
        card = Rank.NINE of Suit.SPADES,
        advice = "Cash the 9♠ too. That's the seventh trick for your side: your 7♠ contract " +
            "is home.",
    ),
    TutorialStep.PlayStep(
        card = Rank.ACE of Suit.HEARTS,
        advice = "Finish with the A♥, the highest heart left. Eight tricks in all: contract " +
            "made with one to spare.",
    ),
)

/**
 * Shown while a completed trick is held on the felt during the tutorial (the hold is forced on for
 * the whole tutorial hand, so nothing rushes past), keyed by trick number 1–10. Each note explains
 * the outcome of that trick, grounded in the trace documented at the top of this file — do not edit
 * one without the other. In practice only the bot-won tricks (3–6) are ever held: when the human
 * wins a trick it is immediately the human's lead, so no hold applies — the rest are safety notes.
 */
val tutorialTrickNotes: Map<Int, String> = mapOf(
    1 to "Your Joker couldn't lose, and it pulled a trump out of every other hand.",
    2 to "The right bower wins: even Olive's A♠ fell to your J♠.",
    3 to "There it is: Olive's J♣ is the LEFT BOWER, a spade in disguise, and it beat your K♠. " +
        "That was the last trump out against you. Tap the trick to continue.",
    4 to "Olive led the Q♦ and it held: everyone had to follow suit, and your forced J♦ ranks " +
        "below her Queen. In diamonds a Jack is just a Jack: only the black ones are bowers " +
        "this hand. Tap the trick to continue.",
    5 to "Your partner Mabel's K♣ took the trick, and a partner's tricks count towards your " +
        "contract too, so nothing is lost. Tap the trick to continue.",
    6 to "Mabel's A♣ won the trick. You had no clubs, but you threw the Q♥ rather than waste a " +
        "trump on your partner's certain winner. Tap the trick to continue.",
    7 to "Your K♥ topped Mabel's J♥, though the trick was staying on your side either way.",
    8 to "No trumps are left outside your hand, so the 10♠ walked it.",
    9 to "The 9♠ was just as unbeatable, and that's the seventh trick: contract secured.",
    10 to "The A♥ took the last trick: eight in all, 7♠ made with a trick to spare.",
)

/** Bubble text once the scripted hand is over, behind the hand-result dialog; also narrated. */
const val TUTORIAL_HAND_DONE = "That's the whole hand. See how it scored."

/** One narrated tutorial line: [id] is the stable stem of its audio asset (files/narration/<id>.mp3). */
data class NarrationLine(val id: String, val text: String)

// Declared before tutorialNarration below: top-level initializers run in file order, and
// speechText needs these at class-init time.
private val CARD_NOTATION = Regex("(10|[2-9AKQJ])([♠♥♦♣])")
private val NO_TRUMP_BID = Regex("\\b(10|[6-9])NT\\b")
private val PLUS_POINTS = Regex("\\+(\\d+)")

/** Phrase-level speech substitutions where synthesizers stumble on the written form. */
private val SPEECH_SUBSTITUTIONS = listOf(
    // A bare "10" in this idiom draws an awkward pause; the word flows.
    "score 10 a trick" to "score ten a trick",
    // Reading the parenthetical verbatim repeats the word: "seven, seven of spades or higher".
    "seven (7♠ or higher)" to "7♠ or higher",
)

/**
 * An all-caps EMPHASIS word ("JACKS OUTRANK THE ACE", "BLACK"). Synthesizers read these as
 * acronyms or letter-spell them ("B-lack"); spoken text folds them to lowercase. Runs after the
 * notation rules, so "NT" is already "no trumps" by then.
 */
private val SHOUTED_WORD = Regex("\\b[A-Z]{2,}\\b")

// Every display text the tutorial shows, with the stable id of its narration clip. The clip audio
// is pre-generated from these by scripts/generate-narration.sh (Piper TTS); NarrationManifestTest
// fails the build if a text changes without regenerating, so the voice can never drift from the
// words on screen.
private val narrationSources: List<Pair<String, String>> = buildList {
    tutorialPrologue.forEachIndexed { i, page -> add("primer-${i + 1}" to page.body) }
    tutorialSteps.forEachIndexed { i, step -> add("step-${i + 1}" to step.advice) }
    tutorialTrickNotes.entries.sortedBy { it.key }.forEach { (n, note) -> add("trick-$n" to note) }
    tutorialEpilogue.forEachIndexed { i, page -> add("epilogue-${i + 1}" to page.body) }
    add("completion" to TUTORIAL_COMPLETION)
    add("hand-done" to TUTORIAL_HAND_DONE)
}

/** Every narration line as the synthesizer should speak it. Consumed by the generator and gate. */
val tutorialNarration: List<NarrationLine> =
    narrationSources.map { (id, display) -> NarrationLine(id, speechText(display)) }

private val narrationIdByDisplay: Map<String, String> =
    narrationSources.associate { (id, display) -> display to id }

/**
 * The narration clip for a display text the tutorial UI is showing, or null for dynamic texts
 * (e.g. the bubble's interpolated fallback) that have no pre-generated clip.
 */
fun narrationIdFor(displayText: String): String? = narrationIdByDisplay[displayText]

/**
 * Expands card-table notation for the synthesizer: "J♠" → "jack of spades", "10NT" →
 * "10 no trumps", "+140" → "plus 140". Everything else is spoken as written.
 */
fun speechText(display: String): String = SPEECH_SUBSTITUTIONS
    .fold(display) { text, (from, to) -> text.replace(from, to) }
    .replace(CARD_NOTATION) { m ->
        val rank = when (val r = m.groupValues[1]) {
            "A" -> "ace"; "K" -> "king"; "Q" -> "queen"; "J" -> "jack"
            else -> r
        }
        val suit = when (m.groupValues[2]) {
            "♠" -> "spades"; "♥" -> "hearts"; "♦" -> "diamonds"; else -> "clubs"
        }
        "$rank of $suit"
    }
    .replace(NO_TRUMP_BID) { m -> "${m.groupValues[1]} no trumps" }
    .replace(PLUS_POINTS) { m -> "plus ${m.groupValues[1]}" }
    .replace(SHOUTED_WORD) { m -> m.value.lowercase() }

/**
 * The live tutorial state handed to [GameScreen]: the index of the next human decision in
 * [tutorialSteps], and how to advance it once that decision is taken.
 */
class TutorialScriptState(val stepIndex: Int, val onAdvance: () -> Unit) {
    /** The pending human decision, or null once the scripted hand is over. */
    val step: TutorialStep? get() = tutorialSteps.getOrNull(stepIndex)
}
