// SPDX-License-Identifier: GPL-3.0-or-later WITH LicenseRef-cardkit-ads-exception
package io.github.rotundtapir.fivehundred.ui

import io.github.rotundtapir.cardkit.core.Card
import io.github.rotundtapir.cardkit.core.Joker
import io.github.rotundtapir.cardkit.core.Rank
import io.github.rotundtapir.cardkit.core.Suit
import io.github.rotundtapir.cardkit.core.of
import io.github.rotundtapir.fivehundred.engine.Bid
import io.github.rotundtapir.fivehundred.engine.Trump

/**
 * The interactive "How to play" tutorial: a real 4-player hand on a fixed seed, replayed through the
 * normal [io.github.rotundtapir.fivehundred.GameViewModel] wiring, with a guidance panel explaining
 * every human decision and only the scripted action enabled — so the hand always follows the script.
 *
 * The script below is the exact trace of seed [TUTORIAL_SEED] with the default table (4 players,
 * 2 teams, misère and no-trumps enabled) and the standard bots at seats 1–3. It was generated by
 * `ai/src/test/.../TutorialTraceGenerator.kt` (kept, @Disabled, as documentation):
 *
 *   Bots: seat 1 = Olive, seat 2 = Mabel (your partner), seat 3 = Edna
 *   Your deal: 10♠ J♠ J♦ 9♠ 5♣ K♠ 7♦ Q♥ Joker A♥ · kitty: Q♣ 8♣ K♥
 *   Auction: Olive Pass · Mabel 6♥ · Edna Pass · You 7♠ · Mabel Pass
 *   Discards: 5♣ 7♦ 8♣
 *   Tricks (your card first marked): Joker✓ · J♠✓ · K♠ (Olive's J♣ wins) · J♦ (Olive wins) ·
 *     Q♣ (Mabel wins) · Q♥ (Mabel wins) · K♥✓ · 10♠✓ · 9♠✓ · A♥✓  — 8 tricks, 7♠ made, +140/+20.
 *
 * If the game ever deviates from this script, the seed or the ViewModel wiring changed — regenerate.
 */
const val TUTORIAL_SEED = 9L

/** One human decision in the scripted tutorial hand, with the advice shown before it is taken. */
sealed interface TutorialStep {
    val advice: String

    /** The auction: only [bid] is enabled. */
    data class BidStep(val bid: Bid, override val advice: String) : TutorialStep

    /** The kitty exchange: only [cards] are selectable, and all three must be selected. */
    data class DiscardStep(val cards: List<Card>, override val advice: String) : TutorialStep

    /** A trick: only [card] is playable. */
    data class PlayStep(val card: Card, override val advice: String) : TutorialStep
}

/** Shown in the confirmation dialog before the tutorial hand is dealt. */
const val TUTORIAL_INTRO =
    "The tutorial deals a practice hand against three bots and guides every decision — " +
        "what to bid, what to discard, and which card to play, with the reason why. " +
        "Only the recommended move is enabled at each step, so you can't go wrong."

/** Shown after the scripted hand has been scored. */
const val TUTORIAL_COMPLETION =
    "You bid 7♠, drew trumps with the Joker and the bowers, and took eight tricks with your " +
        "partner — contract made, +140 points. You've now seen bidding, the kitty exchange, " +
        "the bowers, following suit, and playing with a partner. " +
        "Start a real game from the home screen when you're ready!"

/**
 * Every human decision of the tutorial hand, in order: 1 bid, 1 discard, 10 plays.
 * The advice is grounded in the actual trace documented above — do not edit one without the other.
 */
val tutorialSteps: List<TutorialStep> = listOf(
    TutorialStep.BidStep(
        bid = Bid.Named(7, Trump.SPADES),
        advice = "Look at your spades: the Joker, the J♠ (the \"right bower\"), K♠, 10♠ and 9♠ — " +
            "five top trumps, plus the A♥ on the side. That's worth about seven tricks, so " +
            "outbid Mabel's 6♥ with 7♠.",
    ),
    TutorialStep.DiscardStep(
        cards = listOf(
            Rank.FIVE of Suit.CLUBS,
            Rank.SEVEN of Suit.DIAMONDS,
            Rank.EIGHT of Suit.CLUBS,
        ),
        advice = "Winning the auction gave you the kitty: Q♣, 8♣ and K♥. Keep every trump and " +
            "your high cards — throw the three weakest odd cards, the 5♣, 7♦ and 8♣. " +
            "Short side suits let you trump those suits sooner.",
    ),
    TutorialStep.PlayStep(
        card = Joker,
        advice = "As declarer you lead the first trick. Start with the Joker — the highest trump " +
            "in the game. It cannot lose, and it pulls a trump out of every other hand.",
    ),
    TutorialStep.PlayStep(
        card = Rank.JACK of Suit.SPADES,
        advice = "Keep drawing trumps with the J♠ — the right bower, the second-highest trump. " +
            "Not even the A♠ can beat it: when spades are trumps, both bowers rank above the ace.",
    ),
    TutorialStep.PlayStep(
        card = Rank.KING of Suit.SPADES,
        advice = "Lead the K♠ to keep clearing trumps. One danger is still out: the J♣ — the " +
            "\"left bower\", the same-colour Jack — counts as a spade and beats your King. " +
            "If it takes this trick, that's a cheap price for flushing it out.",
    ),
    TutorialStep.PlayStep(
        card = Rank.JACK of Suit.DIAMONDS,
        advice = "You must follow suit when you can: Olive led diamonds and the J♦ is your only " +
            "one. Here it's just an ordinary Jack — only the same-colour J♣ becomes a trump.",
    ),
    TutorialStep.PlayStep(
        card = Rank.QUEEN of Suit.CLUBS,
        advice = "Forced again — the Q♣ is your only club. Your partner Mabel's K♣ is winning " +
            "the trick, and her tricks count towards your contract too.",
    ),
    TutorialStep.PlayStep(
        card = Rank.QUEEN of Suit.HEARTS,
        advice = "You're out of clubs, so you could trump — but Mabel's A♣ already has the trick " +
            "and she's your partner. Never trump your partner's winner: throw your lowest card, " +
            "the Q♥.",
    ),
    TutorialStep.PlayStep(
        card = Rank.KING of Suit.HEARTS,
        advice = "Mabel's J♥ is heading for the trick, so play your cheaper heart, the K♥. " +
            "Either way this trick stays on your side — and the A♥ is saved as a certain " +
            "winner for later.",
    ),
    TutorialStep.PlayStep(
        card = Rank.TEN of Suit.SPADES,
        advice = "Count the trumps: every one outside your hand has now been played. Your 10♠ " +
            "and 9♠ are unbeatable — lead the 10♠.",
    ),
    TutorialStep.PlayStep(
        card = Rank.NINE of Suit.SPADES,
        advice = "Cash the 9♠ too. That's the seventh trick for your side — your 7♠ contract " +
            "is home.",
    ),
    TutorialStep.PlayStep(
        card = Rank.ACE of Suit.HEARTS,
        advice = "Finish with the A♥ — the highest heart left. Eight tricks in all: contract " +
            "made with one to spare.",
    ),
)

/**
 * The live tutorial state handed to [GameScreen]: the index of the next human decision in
 * [tutorialSteps], and how to advance it once that decision is taken.
 */
class TutorialScriptState(val stepIndex: Int, val onAdvance: () -> Unit) {
    /** The pending human decision, or null once the scripted hand is over. */
    val step: TutorialStep? get() = tutorialSteps.getOrNull(stepIndex)
}
