#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later WITH LicenseRef-cardkit-ads-exception
#
# Regenerates the tutorial's voice narration from the texts in shared/.../ui/Tutorial.kt.
# Run whenever a narrated tutorial text changes — NarrationManifestTest fails the build until the
# clips match the words again. Commit the resulting MP3s + manifest.txt.
#
# Pipeline: a shared unit test dumps the (id, speech-text) lines to build/narration-texts.tsv;
# Chatterbox TTS (Resemble AI, MIT — chosen by ear over Piper and Kokoro in the 2026-07-12
# audition) synthesizes each line; ffmpeg encodes mono MP3s into the shared module's compose
# resources; each text's SHA-256 lands in manifest.txt for the drift gate.
#
# Chatterbox is a 0.5B model: on CUDA the full set renders in ~2 minutes, on CPU it takes HOURS.
# Run this script on a machine with an NVIDIA GPU (it falls back to CPU with a warning). If the
# GPU lives elsewhere, run the script there and copy the narration directory back — the manifest
# travels with the clips.
#
# Re-rolling: Chatterbox SAMPLES, so a take can come out mangled ("outrank" as an acronym) with
# nothing wrong in the text. Pass clip ids to regenerate just those lines with a fresh roll:
#   scripts/generate-narration.sh step-4 step-5
# Partial re-rolls require the texts to be unchanged (the manifest hash is checked); after any
# text edit, run the full regeneration instead.
#
# One-time setup (on the rendering machine):
#   python3 -m venv ~/.venvs/chatterbox && ~/.venvs/chatterbox/bin/pip install chatterbox-tts soundfile
#   ffmpeg on PATH
#   (Python 3.14: spacy_pkuseg has no wheel — needs gcc to build; triton's JIT needs python3-devel.)
set -euo pipefail
cd "$(dirname "$0")/.."

PYTHON="${PYTHON:-$HOME/.venvs/chatterbox/bin/python}"
OUT=shared/src/commonMain/composeResources/files/narration
TEXTS=shared/build/narration-texts.tsv

[ -x "$PYTHON" ] || { echo "chatterbox venv python not found at $PYTHON (see setup in this script's header)"; exit 1; }
command -v ffmpeg >/dev/null || { echo "ffmpeg not on PATH"; exit 1; }

echo "Dumping narration texts from Tutorial.kt…"
./gradlew -q :shared:testDebugUnitTest --tests '*NarrationManifestTest.dump*' >/dev/null

# Re-roll mode: keep only the requested ids, and require their manifest hashes to be current —
# a partial regen over changed text would silently desync every other clip.
if [ "$#" -gt 0 ]; then
  MANIFEST_FILE="$OUT/manifest.txt"
  [ -f "$MANIFEST_FILE" ] || { echo "no manifest — run a full generation first"; exit 1; }
  FILTERED=$(mktemp)
  for id in "$@"; do
    line=$(grep -P "^${id}\t" "$TEXTS") || { echo "unknown clip id: $id"; exit 1; }
    text=${line#*$'\t'}
    have=$(grep "^${id} " "$MANIFEST_FILE" | cut -d' ' -f2)
    want=$(printf '%s' "$text" | sha256sum | cut -d' ' -f1)
    [ "$have" = "$want" ] || { echo "text for $id changed since the last full run — regenerate everything"; exit 1; }
    printf '%s\n' "$line" >> "$FILTERED"
  done
  TEXTS="$FILTERED"
  echo "Re-rolling: $*"
fi

WAVDIR=$(mktemp -d)
trap 'rm -rf "$WAVDIR"' EXIT

echo "Synthesizing with Chatterbox…"
TEXTS="$TEXTS" WAVDIR="$WAVDIR" "$PYTHON" - <<'PYEOF'
import os
import perth
# perth's implicit watermarker does not load on Python 3.14; the shipped dummy keeps generation
# working. (The watermark is an optional provenance feature of the library, not a license term.)
perth.PerthImplicitWatermarker = perth.DummyWatermarker
import torch
import soundfile as sf
from chatterbox.tts import ChatterboxTTS

device = "cuda" if torch.cuda.is_available() else "cpu"
if device == "cpu":
    print("WARNING: no CUDA device — this will take hours; render on the GPU box instead.")
model = ChatterboxTTS.from_pretrained(device=device)
for line in open(os.environ["TEXTS"]):
    line = line.rstrip("\n")
    if not line:
        continue
    id_, text = line.split("\t", 1)
    wav = model.generate(text)
    sf.write(f"{os.environ['WAVDIR']}/{id_}.wav", wav.squeeze(0).cpu().numpy(), model.sr)
    print(f"  {id_}: {wav.shape[1] / model.sr:.1f}s")
PYEOF

mkdir -p "$OUT"
if [ "$#" -eq 0 ]; then
  # Full run: clips and manifest are rebuilt together.
  rm -f "$OUT"/*.mp3
  MANIFEST="$OUT/manifest.txt"
  {
    echo "# Generated by scripts/generate-narration.sh — do not edit."
    echo "# engine: chatterbox-tts (default voice)"
  } > "$MANIFEST"
fi

count=0
while IFS=$'\t' read -r id text; do
  [ -n "$id" ] || continue
  ffmpeg -y -loglevel error -i "$WAVDIR/$id.wav" -ac 1 -b:a 48k "$OUT/$id.mp3"
  if [ "$#" -eq 0 ]; then
    printf '%s %s\n' "$id" "$(printf '%s' "$text" | sha256sum | cut -d' ' -f1)" >> "$MANIFEST"
  fi
  count=$((count + 1))
done < "$TEXTS"

echo "Generated $count clips into $OUT ($(du -sh "$OUT" | cut -f1))."
