#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later WITH LicenseRef-cardkit-ads-exception
#
# Regenerates the tutorial's voice narration from the texts in shared/.../ui/Tutorial.kt.
# Run whenever a narrated tutorial text changes — NarrationManifestTest fails the build until the
# clips match the words again. Commit the resulting MP3s + manifest.txt.
#
# Pipeline: a shared unit test dumps the (id, speech-text) lines to build/narration-texts.tsv;
# Piper TTS (local, FOSS) synthesizes each line to WAV; ffmpeg encodes mono MP3s into the shared
# module's compose resources; each text's SHA-256 lands in manifest.txt for the drift gate.
#
# One-time setup:
#   python3 -m venv ~/.venvs/piper && ~/.venvs/piper/bin/pip install piper-tts
#   ~/.venvs/piper/bin/python -m piper.download_voices "$VOICE"   (into ~/.cache/piper-voices)
#   ffmpeg on PATH
set -euo pipefail
cd "$(dirname "$0")/.."

VOICE="${VOICE:-en_GB-cori-high}"
PIPER="${PIPER:-$HOME/.venvs/piper/bin/piper}"
MODEL="${MODEL:-$HOME/.cache/piper-voices/$VOICE.onnx}"
OUT=shared/src/commonMain/composeResources/files/narration
TEXTS=shared/build/narration-texts.tsv

[ -x "$PIPER" ] || { echo "piper not found at $PIPER (see setup in this script's header)"; exit 1; }
[ -f "$MODEL" ] || { echo "voice model not found at $MODEL (see setup in this script's header)"; exit 1; }
command -v ffmpeg >/dev/null || { echo "ffmpeg not on PATH"; exit 1; }

echo "Dumping narration texts from Tutorial.kt…"
./gradlew -q :shared:testDebugUnitTest --tests '*NarrationManifestTest.dump*' >/dev/null

mkdir -p "$OUT"
rm -f "$OUT"/*.mp3
MANIFEST="$OUT/manifest.txt"
{
  echo "# Generated by scripts/generate-narration.sh — do not edit."
  echo "# voice: $VOICE"
} > "$MANIFEST"

WAV=$(mktemp --suffix=.wav)
trap 'rm -f "$WAV"' EXIT
count=0
while IFS=$'\t' read -r id text; do
  [ -n "$id" ] || continue
  printf '%s\n' "$text" | "$PIPER" -m "$MODEL" -f "$WAV" >/dev/null 2>&1
  ffmpeg -y -loglevel error -i "$WAV" -ac 1 -b:a 48k "$OUT/$id.mp3"
  printf '%s %s\n' "$id" "$(printf '%s' "$text" | sha256sum | cut -d' ' -f1)" >> "$MANIFEST"
  count=$((count + 1))
done < "$TEXTS"

echo "Generated $count clips into $OUT ($(du -sh "$OUT" | cut -f1))."
