#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later WITH LicenseRef-cardkit-ads-exception
#
# Regenerates the tutorial's voice narration from the texts in shared/.../ui/Tutorial.kt.
# Run whenever a narrated tutorial text changes — NarrationManifestTest fails the build until the
# clips match the words again. Commit the resulting MP3s + manifest.txt.
#
# Pipeline: a shared unit test dumps the (id, speech-text) lines to build/narration-texts.tsv;
# Qwen3-TTS (Apache-2.0 — chosen by ear over Piper, Kokoro and Chatterbox in the 2026-07-12
# audition; Higgs v3 was disqualified by its non-commercial license) synthesizes each line with
# the Aiden voice; ffmpeg encodes mono MP3s into the shared module's compose resources; each
# text's SHA-256 lands in manifest.txt for the drift gate.
#
# The model is 1.7B: on CUDA the full set renders in ~10 minutes; CPU is impractical. Run this
# script on a machine with an NVIDIA GPU. If the GPU lives elsewhere, run the script there and
# copy the narration directory back — the manifest travels with the clips.
#
# Re-rolling: generation samples, so a take can occasionally come out mangled with nothing wrong
# in the text. Pass clip ids to regenerate just those lines with a fresh roll:
#   scripts/generate-narration.sh step-4 step-5
# Partial re-rolls require the texts to be unchanged (the manifest hash is checked); after any
# text edit, run the full regeneration instead.
#
# One-time setup (on the rendering machine):
#   python3 -m venv ~/.venvs/qwen-tts && ~/.venvs/qwen-tts/bin/pip install -U qwen-tts soundfile
#   ffmpeg on PATH
set -euo pipefail
cd "$(dirname "$0")/.."

PYTHON="${PYTHON:-$HOME/.venvs/qwen-tts/bin/python}"
VOICE="${VOICE:-Aiden}"
INSTRUCT="${INSTRUCT:-Clear and concise, explaining a new concept.}"
OUT=shared/src/commonMain/composeResources/files/narration
TEXTS=shared/build/narration-texts.tsv

[ -x "$PYTHON" ] || { echo "qwen-tts venv python not found at $PYTHON (see setup in this script's header)"; exit 1; }
command -v ffmpeg >/dev/null || { echo "ffmpeg not on PATH"; exit 1; }

echo "Dumping narration texts from Tutorial.kt…"
./gradlew -q :shared:testDebugUnitTest --tests '*NarrationManifestTest.dump*' >/dev/null

# Re-roll mode: keep only the requested ids, and require their manifest hashes to be current —
# a partial regen over changed text would silently desync every other clip.
if [ "$#" -gt 0 ]; then
  MANIFEST_FILE="$OUT/manifest.txt"
  [ -f "$MANIFEST_FILE" ] || { echo "no manifest — run a full generation first"; exit 1; }
  FILTERED=$(mktemp)
  for id in "$@"; do
    line=$(grep -P "^${id}\t" "$TEXTS") || { echo "unknown clip id: $id"; exit 1; }
    text=${line#*$'\t'}
    have=$(grep "^${id} " "$MANIFEST_FILE" | cut -d' ' -f2)
    want=$(printf '%s' "$text" | sha256sum | cut -d' ' -f1)
    [ "$have" = "$want" ] || { echo "text for $id changed since the last full run — regenerate everything"; exit 1; }
    printf '%s\n' "$line" >> "$FILTERED"
  done
  TEXTS="$FILTERED"
  echo "Re-rolling: $*"
fi

WAVDIR=$(mktemp -d)
trap 'rm -rf "$WAVDIR"' EXIT

echo "Synthesizing with Qwen3-TTS ($VOICE)…"
TEXTS="$TEXTS" WAVDIR="$WAVDIR" VOICE="$VOICE" INSTRUCT="$INSTRUCT" "$PYTHON" - <<'PYEOF'
import os
import torch
import soundfile as sf
from qwen_tts import Qwen3TTSModel

if not torch.cuda.is_available():
    raise SystemExit("no CUDA device — render on the GPU box instead (see script header)")
# float16 also covers pre-Ampere GPUs (no bf16 on Turing, e.g. the 2080 Ti).
model = Qwen3TTSModel.from_pretrained(
    "Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice",
    device_map="cuda:0",
    dtype=torch.float16,
)
for line in open(os.environ["TEXTS"]):
    line = line.rstrip("\n")
    if not line:
        continue
    id_, text = line.split("\t", 1)
    wavs, sr = model.generate_custom_voice(
        text=text, language="English", speaker=os.environ["VOICE"], instruct=os.environ["INSTRUCT"],
    )
    sf.write(f"{os.environ['WAVDIR']}/{id_}.wav", wavs[0], sr)
    print(f"  {id_}: {len(wavs[0]) / sr:.1f}s")
PYEOF

mkdir -p "$OUT"
if [ "$#" -eq 0 ]; then
  # Full run: clips and manifest are rebuilt together.
  rm -f "$OUT"/*.mp3
  MANIFEST="$OUT/manifest.txt"
  {
    echo "# Generated by scripts/generate-narration.sh — do not edit."
    echo "# engine: qwen3-tts-1.7b-customvoice, voice: $VOICE, instruct: $INSTRUCT"
  } > "$MANIFEST"
fi

count=0
while IFS=$'\t' read -r id text; do
  [ -n "$id" ] || continue
  ffmpeg -y -loglevel error -i "$WAVDIR/$id.wav" -ac 1 -b:a 48k "$OUT/$id.mp3"
  if [ "$#" -eq 0 ]; then
    printf '%s %s\n' "$id" "$(printf '%s' "$text" | sha256sum | cut -d' ' -f1)" >> "$MANIFEST"
  fi
  count=$((count + 1))
done < "$TEXTS"

echo "Generated $count clips into $OUT ($(du -sh "$OUT" | cut -f1))."
